import Index from './index'
import '../styles/global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Index />
      </body>
    </html>
  );
}